// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBODpx_ESZxzR2jZBiy6O6-2gpDVwCQfd8',
    appId: '1:139561676067:web:c364a4880d58360d4ff096',
    messagingSenderId: '139561676067',
    projectId: 'mindsageauth',
    authDomain: 'mindsageauth.firebaseapp.com',
    storageBucket: 'mindsageauth.appspot.com',
    measurementId: 'G-D07V2HNGZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARvC_jtD8HAeLmSqBgWLQO6qEE6bttIbA',
    appId: '1:139561676067:android:9c59318bd4f1ef4e4ff096',
    messagingSenderId: '139561676067',
    projectId: 'mindsageauth',
    storageBucket: 'mindsageauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBgqltMtJGG8RMqfMpHJd2krNnubFx94E',
    appId: '1:139561676067:ios:523c28992df5f8da4ff096',
    messagingSenderId: '139561676067',
    projectId: 'mindsageauth',
    storageBucket: 'mindsageauth.appspot.com',
    iosBundleId: 'com.example.mindSage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBgqltMtJGG8RMqfMpHJd2krNnubFx94E',
    appId: '1:139561676067:ios:523c28992df5f8da4ff096',
    messagingSenderId: '139561676067',
    projectId: 'mindsageauth',
    storageBucket: 'mindsageauth.appspot.com',
    iosBundleId: 'com.example.mindSage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBODpx_ESZxzR2jZBiy6O6-2gpDVwCQfd8',
    appId: '1:139561676067:web:bd77e087606376344ff096',
    messagingSenderId: '139561676067',
    projectId: 'mindsageauth',
    authDomain: 'mindsageauth.firebaseapp.com',
    storageBucket: 'mindsageauth.appspot.com',
    measurementId: 'G-1DPT2MWMJ1',
  );

}